name: Build and Publish
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name : Validate Gradle Wrapper
        uses : gradle/wrapper-validation-action@v1
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          cache: gradle
          java-version: 17
          
      - name: Clean Build
        run: ./gradlew clean build --no-daemon

      - name: Get Mod Info
        id: get_mod_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_name mod_version minecraft_version'
        
      - name: Publish to Modrinth and Curseforge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          name: ${{ steps.get_mod_info.outputs.mod_name }} ${{ steps.get_mod_info.outputs.mod_version }} for Minecraft ${{ steps.get_mod_info.outputs.minecraft_version }}
          loaders: fabric
          files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
        
          modrinth-id: dv1QW2PN
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 683156
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
